### ISSUE TITLE
macOS Compatibility Issues

### ISSUE THREAD

**Issue by ncsolar** [sdatkinson/iPlug2#13]
Hello,

I created two Pull requests to fix issues with macOS:

1- Replace all occurrences of 'std::exception("message")' Error: "No matching conversion for functional-style cast from 'const char[76]' to 'std::exception'"

2- Update ../scripts/prepare_resources-mac.py Error: Multiple errors related to Python 3

Thanks!

**Comment by sdatkinson** [comment]
Closing in preparation for archiving project
