### ISSUE TITLE
wrapping DSP to a namespace

### ISSUE THREAD

**Issue by masqutti** [sdatkinson/iPlug2#14]
I think it would be a decent idea to wrap DSP into it's own namespace other than just DSP, since it is such a widely used shorthand name. I looked the sources and many others seemed to have a-ok names so just an idea! I had to modify em manually to fit on my own project.

Thank you for your hard work, this thing is awesome! :)

**Comment by sdatkinson** [comment]
Closing in preparation for archiving project
